apiVersion: v1
kind: Service
metadata:
  name: ftp-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ftp
    port: 21
    protocol: TCP
    targetPort: 21
  - name: passive-ftp
    port: 30101
    protocol: TCP
    targetPort: 30101
  - name: passive-ftp2
    port: 30102
    protocol: TCP
    targetPort: 30102
  - name: passive-ftp3
    port: 30103
    protocol: TCP
    targetPort: 30103
  - name: passive-ftp4
    port: 30104
    protocol: TCP
    targetPort: 30104
  - name: passive-ftp5
    port: 30105
    protocol: TCP
    targetPort: 30105
  - name: passive-ftp6
    port: 30106
    protocol: TCP
    targetPort: 30106
  - name: passive-ftp7
    port: 30107
    protocol: TCP
    targetPort: 30107
  - name: passive-ftp8
    port: 30108
    protocol: TCP
    targetPort: 30108
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ftp-server
  sessionAffinity: None
  type: NodePort
