apiVersion: v1
kind: Service
metadata:
  labels:
    app: halting-wolf-redis
    chart: redis-1.1.1
    heritage: Tiller
    release: halting-wolf
  name: halting-wolf-redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: halting-wolf-redis
  sessionAffinity: None
  type: ClusterIP
