apiVersion: v1
data:
  default.conf: "server {\n    listen       80;\n    server_name  video.bestadultnetwork.com;\n\
    \n    access_log  /var/log/nginx/access.log  main;\n\n    root\t/home/ftpusers/banadultvideo;\n\
    \n    location / {\n        autoindex\toff;\n    }\n\n}\n"
kind: ConfigMap
metadata:
  name: nginx.conf
