apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '19'
  labels:
    app: karma
  name: karma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karma
    spec:
      containers:
      - image: drs.gingerapp.com/php54:1.1
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          name: karma
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www
          name: wp-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: seckey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 33
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wp-storage
        persistentVolumeClaim:
          claimName: nfs-pvc-wp
