apiVersion: v1
kind: Service
metadata:
  labels:
    app: karma
  name: karma
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30280
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: karma
  sessionAffinity: None
  type: LoadBalancer
