apiVersion: v1
kind: Service
metadata:
  labels:
    app: plesk
  name: plesk-apache
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30580
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: plesk
  sessionAffinity: None
  type: LoadBalancer
