apiVersion: v1
kind: Service
metadata:
  labels:
    app: plesk-main
  name: plesk2-apache
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30780
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: plesk-main
  sessionAffinity: None
  type: LoadBalancer
