apiVersion: v1
kind: Service
metadata:
  labels:
    app: plesk
  name: plesk
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30880
    port: 8880
    protocol: TCP
    targetPort: 8880
  selector:
    app: plesk
  sessionAffinity: None
  type: LoadBalancer
