apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '3'
  labels:
    app: plesk-adult
  name: plesk-adult
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plesk-adult
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plesk-adult
    spec:
      containers:
      - image: drs.gingerapp.com/plesk-img:2.4
        imagePullPolicy: Always
        name: plesk-main
        ports:
        - containerPort: 8880
          name: plesk
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /init
          name: plesk-init-ga
        - mountPath: /var/lib
          name: db-plesk
        - mountPath: /var/www
          name: ws-plesk
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: key2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 488
          items:
          - key: run.sh
            path: run.sh
          name: plesk-run-ga
        name: plesk-init-ga
      - name: db-plesk
        persistentVolumeClaim:
          claimName: nfs-pvc-pl-db-adult
      - name: ws-plesk
        persistentVolumeClaim:
          claimName: nfs-pvc-pl-adult
