apiVersion: v1
kind: Service
metadata:
  labels:
    app: plesk-adult
  name: plesk-adult-apache
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: plesk-adult
  sessionAffinity: None
  type: LoadBalancer
