apiVersion: v1
kind: Service
metadata:
  labels:
    app: plesk-adult
  name: plesk-adult
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30980
    port: 8880
    protocol: TCP
    targetPort: 8880
  selector:
    app: plesk-adult
  sessionAffinity: None
  type: LoadBalancer
