apiVersion: v1
kind: Service
metadata:
  labels:
    app: pornkapp
  name: pornk-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pornkapp
  sessionAffinity: None
  type: NodePort
