apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  labels:
    app: sogninascostiapp
  name: sogninascostiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sogninascostiapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sogninascostiapp
    spec:
      containers:
      - image: drs.gingerapp.com/sogninascosti_web
        imagePullPolicy: IfNotPresent
        name: sogninascostiapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/wwwroot/sitemap
          name: sitemap
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: key1
      nodeSelector:
        dedicated: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sitemap
        persistentVolumeClaim:
          claimName: nfs-pvc-adult
