apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
    task: monitoring
  name: monitoring-influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    k8s-app: influxdb
  sessionAffinity: None
  type: ClusterIP
